# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-08 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(default='', null=True, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remark',
            field=models.TextField(default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.TextField(default='', null=True, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='city',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='remark',
            field=models.TextField(default='', null=True, verbose_name='备注'),
        ),
    ]
