# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-09 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20180608_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrebate',
            name='activity_type',
            field=models.CharField(max_length=32, null=True, verbose_name='活动类型'),
        ),
        migrations.AlterField(
            model_name='equipmentrebate',
            name='agent_id',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='代理商ID'),
        ),
        migrations.AlterField(
            model_name='equipmentrebate',
            name='agent_name',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='代理商名称'),
        ),
        migrations.AlterField(
            model_name='equipmentrebate',
            name='bind_time',
            field=models.DateField(blank=True, null=True, verbose_name='绑定时间'),
        ),
        migrations.AlterField(
            model_name='equipmentrebate',
            name='is_rebate',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='是否返利'),
        ),
        migrations.AlterField(
            model_name='equipmentrebate',
            name='name',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='equipmentrebate',
            name='phone',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='注册手机号'),
        ),
        migrations.AlterField(
            model_name='equipmentrebate',
            name='register_time',
            field=models.DateField(blank=True, null=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='equipmentrebate',
            name='remark',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='equipmentrebate',
            name='type',
            field=models.CharField(max_length=32, null=True, verbose_name='号段类型'),
        ),
        migrations.AlterField(
            model_name='equipmenttransaction',
            name='agent_name',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='代理商名称'),
        ),
        migrations.AlterField(
            model_name='equipmenttransaction',
            name='phone',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='注册手机号'),
        ),
        migrations.AlterField(
            model_name='equipmenttransaction',
            name='service_code',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='服务编码'),
        ),
        migrations.AlterField(
            model_name='equipmenttransaction',
            name='transaction_code',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='交易流水号'),
        ),
        migrations.AlterField(
            model_name='equipmenttransaction',
            name='transaction_status',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='equipmenttransaction',
            name='type',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='号段类型'),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后一次登录时间'),
        ),
    ]
