# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-09 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20180609_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrebate',
            name='month',
            field=models.DateField(blank=True, null=True, verbose_name='交易月份'),
        ),
    ]
