# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20180609_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identity',
            field=models.CharField(default='', max_length=24, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='identity',
            field=models.CharField(default='', max_length=24, null=True, verbose_name='身份证号'),
        ),
    ]
