# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-14 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20180613_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.IntegerField(default=0, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='product',
            name='p_type',
            field=models.CharField(default='', max_length=64, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.CharField(default='', max_length=64, verbose_name='供应商'),
        ),
    ]
