# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-14 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_auto_20180614_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=64, verbose_name='编号'),
        ),
    ]
