version: '3.1'

services:
  web:
    restart: always
    build: ./web
    ports:
      - 8000:8000
    links:
      - mysql:mysql
      - redis:redis
    environment:
      - SECRET_KEY=5(15ds+i2+%ik6z&!yer+ga9m=e%jcqiz_5wszg)r-z!2--b2d
      - DB_NAME=crm
      - DB_USER=root
      - DB_PASS=zxcde321BQ
      - DB_HOST=mysql
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_POOL_SIZE=500
      - FILE_HOST=file
      - FILE_PORT=9000
      - FILE_PATH=/file/store
    command: /usr/local/bin/gunicorn wsgi:application -w 2 -b :8000
  
  file:
    restart: always
    build: ./web
    ports:
      - 9000:8000
    links:
      - mysql:mysql
      - redis:redis
    environment:
      - SECRET_KEY=5(15ds+i2+%ik6z&!yer+ga9m=e%jcqiz_5wszg)r-z!2--b2d
      - DB_NAME=crm
      - DB_USER=root
      - DB_PASS=zxcde321BQ
      - DB_HOST=mysql
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_POOL_SIZE=500
      - FILE_HOST=file
      - FILE_PORT=9000
      - FILE_PATH=/file/store
    command: /usr/local/bin/gunicorn wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - /deploy/nginx/cdn:/nginx/cdn:Z
      - /deploy/nginx/logs:/nginx/logs:Z
    links:
      - web:web
  
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
      - --loglevel warning
    volumes:
      - /deploy/redis:/var/lib/redis:Z
    ports:
      - 6379:6379

  mysql:
    restart: always
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=zxcde321BQ
    - DEBUG_COMPOSE_ENTRYPOINT=1
    - MYSQL_GENERAL_LOG=1
    - TIMEZONE=Asia/Shanghai
    volumes:
    - /deploy/mysql/data:/var/lib/mysql:Z
    - /deploy/mysql/log:/var/log/mysql:Z
    ports:
      - 3306:3306

  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=bq
      - POSTGRES_PASSWORD=zxcde321BQ
      - POSTGRES_DB=crm
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /deploy/postgresql:/var/lib/postgresql/data:Z
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
